config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/home'

  match "todos/create" => "todos#create", :via => :post

  root 'welcome#home'

  resources :todos

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin? :admin
         can :manage, :all
      else
         can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles
  has_many :users, :through => :user_roles

end

app/models/todo.rb
class Todo < ActiveRecord::Base

    belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos, dependent: :destroy

  has_many :roles, :through => :user_roles
  has_many :user_roles

  def admin?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

  ROLES = %w[admin moderator author banned]



end

app/models/user_role.rb
class UserRole < ActiveRecord::Base

  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.where({completed: false, user_id: current_user.id})
    @completes = Todo.where({completed: true, user_id: current_user.id})

  end

  def new
    @todo =  Todo.new
  end


  def create
    @todo = Todo.create({:name => params[:todo][:name], :completed => false, :user_id => current_user.id})

    if @todo.save
      redirect_to :action => 'index', :notice => "Your todo item was created!"
    else
      render "index"
    end

  end



  def show
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update_attribute(:completed, true)
      redirect_to :action => 'index', :notice => "Your todo was marked as completed!"
    else
      redirect_to :action => 'index', :notice => "Your todo was unable to be marked as completed!"
    end

  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to :action => 'index', :notice => "Your todo was deleted!"
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
      if user_signed_in?
        redirect_to :controller => 'todos', :action => "index"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MLToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
    You are currently signed in as <%= current_user.email %>, not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

<% else %>
    <%= link_to "Sign up!", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>

<% end %>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo do |form| %>

	<label>Task:
		<p><%= form.text_field :name %></p>
	</label>

	<p><%= form.submit %></p>

<% end %>

app/views/todos/edit.html.erb
<h1>Edit this todo</h1>

<%= render :partial => 'form' %>

app/views/todos/index.html.erb
<title>Todo App </title>
<h1>Todo App</h1>
<p>to-do's</p>

<% @todos.each do |t| %>
  <li>
    <%= t.name %>
    <small><%= link_to "Mark as completed", todo_path(t), :method => :put  %> </small>
    <% if can? :edit, t %>
      <small><%= link_to "Edit", edit_todo_path(t) %> </small>
    <% end %>
  </li>

<% end %>

<p> completed to-do's <p>

<% @completes.each do |t| %>
  <li>
    <%= t.name %>
    <small><%= link_to "Remove", t, :confirm => "Remove this from the list?", :method => :delete  %> </small>
  </li>

<% end %>


<%= link_to "add To-do´s here", new_todo_url %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render :partial => 'form' %>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>